# Generated by Django 4.0.5 on 2022-06-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manime', '0002_auto_20220602_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('episode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manime.episode')),
            ],
        ),
    ]
