# Generated by Django 3.2 on 2022-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manime', '0004_alter_anime_cover_alter_anime_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
